-- Test 1)

INSERT INTO GLOBAL_QUALITY_DB.FACT_QUALITY_SAMPLES (SAM_ID, BAT_COD, CONT_COD, MDF_VAL, FAIL_IND)
VALUES ('S_001', 'BAT_ES_002', 'C_PHOS', 0.75, 1); -- <--- FAIL_IND = 1 if we want a BLOCKED pallet with a MDF_VAL that exceeds


-- Test 2)

INSERT INTO GLOBAL_QUALITY_DB.FACT_QUALITY_SAMPLES (SAM_ID, BAT_COD, CONT_COD, MDF_VAL, FAIL_IND)
VALUES ('S_001', 'BAT_ES_002', 'C_PHOS', 0.00, 0); -- <--- FAIL_IND = 0 if we want a RELEASED pallet
